export const Head = () => {
  return (
    <div>
      <title>Gallemy</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </div>
  );
};
